services:
  - type: web
    name: hangman
    runtime: python
    buildCommand: pip install -r requirements.txt && cd frontend && npm install --legacy-peer-deps && npm run build
    startCommand: gunicorn app:app
    envVars:
      - key: PG_HOST
        sync: false
      - key: PG_PORT
        value: "5432"
      - key: PG_DB
        sync: false
      - key: PG_USER
        sync: false
      - key: PG_PASSWORD
        sync: false
      - key: PYTHON_VERSION
        value: "3.11.0"
